#!/usr/bin/env bash
# Unit tests for doctor --dry-run/--fix contracts and shim repair.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# shellcheck source=test/common/env.sh
# shellcheck disable=SC1091
. "${REPO_ROOT}/test/common/env.sh"
# shellcheck source=test/common/assert.sh
# shellcheck disable=SC1091
. "${REPO_ROOT}/test/common/assert.sh"

test_require_command jq

test_create_tmpdir

printf ' -> doctor rejects --fix + --dry-run\n'
set +e
"${REPO_ROOT}/bin/mcp-bash" doctor --fix --dry-run >/dev/null 2>&1
rc=$?
set -e
assert_eq "2" "${rc}" "expected exit 2 for mutually exclusive flags"

printf ' -> stage managed install for shim tests\n'
HOME_ROOT="${TEST_TMPDIR}/home"
export HOME="${HOME_ROOT}"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_BIN_HOME="${HOME}/.local/bin"
mkdir -p "${HOME}/.local/share" "${HOME}/.local/bin"
MANAGED_ROOT="${HOME}/.local/share/mcp-bash"
mkdir -p "${MANAGED_ROOT}"
(
	cd "${REPO_ROOT}" || exit 1
	tar -cf - --exclude .git bin lib VERSION | (cd "${MANAGED_ROOT}" && tar -xf -)
)
printf '%s\n' '{"managed":true}' >"${MANAGED_ROOT}/INSTALLER.json"

if [ -e "${HOME}/.local/bin/mcp-bash" ]; then
	test_fail "shim should not exist before running doctor"
fi

printf ' -> doctor --dry-run --json proposes shim action on managed install\n'
set +e
"${MANAGED_ROOT}/bin/mcp-bash" doctor --dry-run --json >"${TEST_TMPDIR}/doctor_dry.json" 2>/dev/null
rc=$?
set -e
assert_eq "0" "${rc}" "expected dry-run to succeed on managed install"
jq -e '.exitCode == 0' "${TEST_TMPDIR}/doctor_dry.json" >/dev/null
jq -e '.proposedActions | type == "array"' "${TEST_TMPDIR}/doctor_dry.json" >/dev/null
jq -e '.proposedActions[0].id == "shim.ensure"' "${TEST_TMPDIR}/doctor_dry.json" >/dev/null

printf ' -> doctor --fix --json creates shim on managed install\n'
set +e
"${MANAGED_ROOT}/bin/mcp-bash" doctor --fix --json >"${TEST_TMPDIR}/doctor_fix.json" 2>/dev/null
rc=$?
set -e
assert_eq "0" "${rc}" "expected fix to succeed on managed install"
jq -e '.exitCode == 0' "${TEST_TMPDIR}/doctor_fix.json" >/dev/null

shim_path="${HOME}/.local/bin/mcp-bash"
if [ ! -e "${shim_path}" ]; then
	test_fail "expected shim to exist after doctor --fix: ${shim_path}"
fi

case "$(uname -s 2>/dev/null || printf '')" in
MINGW* | MSYS* | CYGWIN*)
	assert_contains "mcp-bash managed shim; generated by doctor --fix" "$(cat "${shim_path}")"
	;;
*)
	if [ ! -L "${shim_path}" ]; then
		test_fail "expected shim to be a symlink on non-MSYS: ${shim_path}"
	fi
	;;
esac

printf 'Doctor mode tests passed.\n'
